#!/usr/bin/python3 - 

def showBanner():
	print('''                                                                 ''') 
	print('''                    _wr""        "-q__                           ''')  
	print('''                 _dP                 9m_     					  ''')
	print('''               _#P                     9#_                       ''')  
	print('''              d#@                       9#m                      ''')  
	print('''             d##                         ###                     ''')  
	print('''            J###                         ###L                    ''')  
	print('''            {###K                       J###K                    ''')  
	print('''            ]####K      ___aaa___      J####F                    ''')  
	print('''        __gmM######_  w#P""   ""9#m  _d#####Mmw__                ''')  
	print('''     _g##############mZ_         __g##############m_             ''')  
	print('''   _d####M@PPPP@@M#######Mmp gm#########@@PPP9@M####m_           ''')  
	print('''  a###""          ,Z"#####@" '######"\g          ""M##m          ''')  
	print(''' J#@"             0L  "*##     ##@"  J#              *#K         ''')  
	print(''' #"               `#    "_gmwgm_~    dF               `#_        ''')  
	print('''7F                 "#_   ]#####F   _dK                 JE        ''')  
	print(''']                    *m__ ##### __g@"                   F        ''')  
	print('''                       "PJ#####LP"                               ''')  
	print('''                         0######_                                ''')  
	print('''                       _0########_                               ''')    
	print('''                     _d#####^#####m__                            ''') 
	print('''      "*w_________am#####P"   ~9#####mw_________w*"              ''')    
	print('''          ""9@#####@M""           ""P@#####@M""                  ''')  